import{a as q,S as M,i as s}from"./assets/vendor-CIF6YjI2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const P="https://pixabay.com/api/",B="24739758-4c739ca612149bb371b205192",m=async(o,t=1)=>(await q.get(P,{params:{key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data,g=document.querySelector(".gallery"),h=document.querySelector(".loader"),p=document.querySelector(".load-more"),R=new M(".gallery a",{captionsData:"alt",captionDelay:250}),$=()=>{g.innerHTML=""},y=o=>{const t=o.map(({webformatURL:n,largeImageURL:c,tags:e,likes:r,views:i,comments:S,downloads:v})=>`
    <li class="gallery-item">
      <a href="${c}" class="gallery-link">
        <img src="${n}" alt="${e}" loading="lazy" class="gallery-image"/>
      </a>
      <div class="info">
        <p><b>Likes</b> ${r}</p>
        <p><b>Views</b> ${i}</p>
        <p><b>Comments</b> ${S}</p>
        <p><b>Downloads</b> ${v}</p>
      </div>
    </li>`).join("");g.insertAdjacentHTML("beforeend",t),R.refresh()},f=()=>{h.classList.remove("is-hidden")},b=()=>{h.classList.add("is-hidden")},L=()=>{p.classList.remove("is-hidden")},d=()=>{p.classList.add("is-hidden")},w=document.querySelector(".form"),x=document.querySelector(".load-more");let l="",a=1,u=0;const O=async o=>{if(o.preventDefault(),l=o.currentTarget.elements["search-text"].value.trim(),!l){s.warning({message:"Please enter a search query.",position:"topRight"});return}a=1,$(),d(),f();try{const t=await m(l,a);if(t.hits.length===0){s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(t.hits),u=Math.ceil(t.totalHits/15),a<u?L():s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{s.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{b(),w.reset()}},E=()=>{const o=document.querySelector(".gallery-item");if(o){const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}},A=async()=>{a+=1,d(),f();try{const o=await m(l,a);y(o.hits),E(),a>=u?(d(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch{s.error({message:"Something went wrong while loading more images.",position:"topRight"})}finally{b()}};w.addEventListener("submit",O);x.addEventListener("click",A);
//# sourceMappingURL=index.js.map
